### ISSUE TITLE
[Bug] Open in integrated terminal opens both the integrated terminal and the native one in a separate window

### ISSUE THREAD

**Issue by vguillet** [polyipseity/obsidian-terminal#1]
Title says it all, im on windows 11 btw. Cheers for the amazing work!

**Comment by polyipseity** [comment]
Thank you!

Do you mean the window that pops up when you start a terminal? That window should disappear by itself. This is the intended behavior as the current implementation requires the window to appear momentarily. (In case you are wondering, it is for obtaining the handle to resize the terminal.) I think I should write down this behavior down somewhere in the `README.md` file.

If the window does not disappear by itself, then it is indeed a bug and I would like some more information like whether Python is installed, plugin settings, etc.

**Comment by vguillet** [comment]
Thanks for the reply. Unfortunately I checked and the window does not disappear. Not sure if it is relevant but the integrated terminal remains empty, and it does not contain the usual:

```
Microsoft Windows [Version 10.0.19045.2486]
(c) Microsoft Corporation. All rights reserved.

C:\Users\....>
```

(that does appear in the external window though)

Hope that helps!

**Comment by polyipseity** [comment]
I think there are two separate bugs here. One is the integrated terminal
not showing anything, another is the external window not hiding.

The latest version (2.8.1) should fix the first problem. (see
459ac226e08bc8898885731a41de6406af10c322)

As for the second problem, my guess is that the Python resizer successfully
starts, but then exits unexpectedly due to an error. You can check if my
guess is correct by setting 'Python executable' to empty. The terminal
should launch successfully.

Since the Python resizer is responsible for hiding the window, the external
window remains visible if the resizer fails.

To fix this problem, you should check whether Python is configured
correctly (see `README.md`):
- Python should be 3.11 or above. You can check by using `python --version`.
- Packages `pywinctl` and `psutil` should be installed. If not, run `pip
install pywinctl psutil`.
- 'Python executable' is configured properly in plugin settings.

Alternatively, you could disable the Python resizer by setting the 'Python
executable' setting to blank. (The terminal experience won't be any good
though.) This will hide the window when spawning the terminal instead of
deferring it to Python.

If the above solution does not work, can you please show messages in the
developer console (press`Ctrl+Shift+I` in Obsidian, then click the
'Console' tab)?

**Comment by polyipseity** [comment]
@vguillet: Any updates?

**Comment by vguillet** [comment]
Sorry, forgot to reply. Unfortunately the issue ist fixed. I think it might have to do with my python version (still on 3.9). That being said its nothing major, and not a breaking issue!

**Comment by polyipseity** [comment]
Alright, I will leave the issue open then to see if anyone else has the
same issue.

**Comment by polyipseity** [comment]
Well, I just tested it on Python 3.9 on Windows 11, and the issue does not
arise. The only problem I can think of left is that `psutil` and `pywinctl`
are not installed. Leaving this here for anyone else coming across this
issue.

If anyone faced the same issue and resolved it by installing `psutil` and
`pywinctl` (run `pip3 install psutil pywinctl`), please comment.

**Comment by polyipseity** [comment]
I forgot about it until now, but I want to tell you that the latest version (3.1.0) fixes another way the window hider can fail.

If the terminal window opens too slowly, the Python script will simply fail and not hide the window. Now the script will wait for the window for 10 seconds before failing. (ba9c34f4be014d641670ba1b01d53ec6d1723c18, 781a4ec764628439aca519d7cc31e69f84e7f00e)

See if this fixes the problem. Thanks!
