### ISSUE TITLE
Feature Request: Start terminal in current directory

### ISSUE THREAD

**Issue by dlccyes** [polyipseity/obsidian-terminal#12]
In VsCode, the terminal will open in the project root, I wish this plugin does the same

**Comment by polyipseity** [comment]
Actually, it is already available in the plugin. If you are talking about commands, you just need to choose the `Open terminal in root directory: (type)` command instead of the `Open terminal: (type)` command. If you are talking about the `Open terminal` ribbon, well yes, you are right. But you can change the working directory using the `Edit` button in the context menu for the terminal tab.

So, I just made some changes to reduce such confusion that will be available in the next release:
- I removed the `Open terminal: Integrated` and `Open terminal: External` commands as the default working directory for them is likely useless. `Open terminal: Select` is kept because it is the only command available on mobile (no such thing as working directory on mobile) and can open developer console, which does not require a working directory. (985b6100ef14e9f0933de0859dd0e8872e217490)
- I changed the `Open terminal` ribbon to use the root directory working directory if available (i.e. not on mobile). (55b917052b371eb566976af7d13b6345c64554ef)

I think these should fix the problems you are having.

**Comment by dlccyes** [comment]
Oh thanks didn't notice the option
