### ISSUE TITLE
cannot open integrated terminal: ImportError: cannot import name 'waitstatus_to_exitcode'

### ISSUE THREAD

**Issue by alligatorjazz** [polyipseity/obsidian-terminal#22]
every time i try to open the integrated terminal, i get the following error in the terminal window:

```
Traceback (most recent call last):
File "<string>", line 2, in <module>
ImportError: cannot import name 'waitstatus_to_exitcode' from 'os' 
(/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/os.py)
```

device: M1 Macbook Air 2020
os: macOS monterey 12.4 beta
obsidian version: 1.3.5
plugin version: 3.9.2

**Comment by polyipseity** [comment]
You are using Python 3.8. If you update your Python to at least 3.9
(recommend 3.10 or above), then it should work as `waitstatus_to_exitcode` (
https://docs.python.org/library/os.html#os.waitstatus_to_exitcode) is only
available starting from Python 3.9.

**Comment by jfines** [comment]
I am having a similar problem on Linux (Ubuntu 20.04). After selecting `"". Integrated. linuxIntegratedDefault.` from the select terminal window (yes the entry looks exactly like that with two double quote chars at the start of the sentence) I get the following output in the terminal window that appears..

```
Traceback (most recent call last):
                                    File "<string>", line 2, in <module>
                                                                        ImportError: cannot import name 'waitstatus_to_exitcode' from 'os' (/usr/lib/python3.8/os.py)
```

Yes it appears exactly like that (see screenshot). Pressing keys on the keyboard does not add input in the window.

When `"". Integrated. linuxIntegratedDefault.` is selected from the select terminal window (yes it looks exactly like that with two double quote chars at the start of the sentence) - I get the following Obsidian message (the ones that appear in Obsidian in the upper right corner)..

```
Spawning terminal: sh
```

And is followed immediately by Obsidian message..

```
Terminal exited: 1
```

The first of these two disappears after about 5 seconds but the second one remains.

When closing the pane (using the "close" menu item in the Obisidian options menu) I get the following Obsidian message..

```
Error killing pseudoterminal
TypeError: Cannot read properties of
undefined (reading 'onRequestRedraw')
```

Screenshots attached:

1. Open pane after selecting integrated terminal in the terminal selection window
2. Menu that is being used to close the pane
3. The terminal selection window as it appears on my system

I have also uploaded an unlisted video that may be seen [here](https://youtu.be/8CerR5RJrSQ). The video does not appear in search results and is only seen by having the link. It demonstrates exactly what I am experiencing - 4 minutes 37 seconds.

![Screenshot from 2023-10-07 23-10-00](https://github.com/polyipseity/obsidian-terminal/assets/86216502/56436b27-f470-42d8-896c-96be0e0c71ce)
![Screenshot from 2023-10-07 23-10-09](https://github.com/polyipseity/obsidian-terminal/assets/86216502/f586c8bd-4976-4960-b6df-f6da399e59cd)
![Screenshot from 2023-10-07 23-11-36](https://github.com/polyipseity/obsidian-terminal/assets/86216502/5e4e4678-504c-445c-b132-56343a8c8c3f)

Its probably user error but I don't know how / in what way it would be - I am not super technical skilled about these things and was hoping this plugin would work for me out of the box. As it stands this plugin is unusable for me and I do not receive the benefit it would have provided - having a terminal in Obsidian. The video gives more detail. If there is any information something I can do to make it work please, someone, let me know. If this is a bug or a problem with the plugin I would love to see it get fixed so that I can have a terminal too :)

Thanks for taking the time to create this. It is a wonderful and very useful idea. I hope to be able to use it too soon.

**Comment by jfines** [comment]
Well, after aaaall that fuss, I looked and I saw the response to the first post and noticed how the solution seemed to be upgrading my python version (I too had phython3.8 at the time). I upgraded to the latest version (python3.12 at time of this writing) and the integrated terminal seems to work fine. The external terminal selection - apparently - still doesn't.

Fwiw, I used the deadsnakes repository to pull in the latest version of python (works for Linux). Here's the [article](https://www.itsupportwale.com/blog/how-to-upgrade-to-python-3-10-on-ubuntu-18-04-and-20-04-lts/) I used and modify instructions in the article for the version you desire.

**Soln:** _Upgrade your python. version._

**Comment by polyipseity** [comment]
20cd6690f68606f1e1ec750acf96270897c37cb4 should help with this by checking for Python and dependency versions when you click the "Check" button in the "Python executable" settings.

**Comment by polyipseity** [comment]
@jfines commented [3 weeks ago](https://github.com/polyipseity/obsidian-terminal/issues/22#issuecomment-1751941414)
> Well, after aaaall that fuss, I looked and I saw the response to the first post and noticed how the solution seemed to be upgrading my python version (I too had phython3.8 at the time). I upgraded to the latest version (python3.12 at time of this writing) and the integrated terminal seems to work fine now. The external terminal selection - apparently - still doesn't.
> 
> Fwiw, I used the deadsnakes repository to pull in the latest version of python (works for Linux). Here's the [article](https://www.itsupportwale.com/blog/how-to-upgrade-to-python-3-10-on-ubuntu-18-04-and-20-04-lts/) I used and modify instructions in the article for the version you desire.
> 
> **Soln: Upgrade your python. version.**

Can you open a separate issue for failing to open the external terminal if you are still here?

**Comment by polyipseity** [comment]
@jfines commented [3 weeks ago](https://github.com/polyipseity/obsidian-terminal/issues/22#issuecomment-1751937407)

> ```
> Error killing pseudoterminal
> TypeError: Cannot read properties of
> undefined (reading 'onRequestRedraw')
> ```

Known issue, see #28. I need to wait for `xterm` to release a new version before I can fix this error. For now, it only affects closing and restarting the terminal.

> I have also uploaded an unlisted video that may be seen [here](https://youtu.be/8CerR5RJrSQ). The video does not appear in search results and is only seen by having the link. It demonstrates exactly what I am experiencing - 4 minutes 37 seconds.

I see what you mean by failing to open the external terminal now. It would be nice if you can provide more information you think that are relevant by opening an new issue.
