### ISSUE TITLE
Open iTerm2 in Macosx?

### ISSUE THREAD

**Issue by mgussekloo** [polyipseity/obsidian-terminal#32]
First of all, thanks for the plugin. 

I'm struggling to have this plugin open iTerm2 on Macosx. How should I configure this? Also, is there a way to remove the "Open in terminal: Select" and "Open in terminal: Integrated" from the context menu?

Apologies if this is obvious, I've spent a fair amount of trying and searching the docs... Thanks for any advice!

**Comment by polyipseity** [comment]
First, can I ask if you are looking to open iTerm as an external terminal instead of an integrated one? Because opening it as an integrated one won't work.

There is no way to only remove the "select" and "integrated" button in the context menu without removing the "external" button in the plugin settings. But I can add the options easily.

**Comment by polyipseity** [comment]
If you are talking about opening iTerm as an external terminal, editing the external terminal profile (for example, `darwinExternalDefault`) to change the executable to `/Applications/iTerm.app/Contents/MacOS/iTerm2` should work.

**Comment by polyipseity** [comment]
Forgot to add that you also need to set the arguments of that profile to have 1 argument with the value `"$PWD"` (including `"`) so that the current directory when you open the external terminal is set up properly.

**Comment by polyipseity** [comment]
I am assuming this works now...
