### ISSUE TITLE
Terminal Plugin Invades the Developer Tools Panel

### ISSUE THREAD

**Issue by RicSanOP** [polyipseity/obsidian-terminal#38]
Hello @polyipseity,

Firstly, I wish to thank you for developing this great plugin. I have been getting a lot of benefit from using nvim with obsidian.nvim in obsidian terminals. I would just like to highlight one issue that I have with the plugin. When using to the developer tools panel to debug any issues I am facing during obsidian configuration (and plugin tweaking), if the terminal plugin is on, all console messages are exclaimed as coming from the terminal plugin itself. I believe this happens due to how you are routing console logs to the developer console that comes with this plugin. Would it be possible to fix this, or perhaps turn off the developer console in the settings so as to avoid this issue? Any help on this matter would be deeply appreciated. I would also be happy to assist in developing such a fix if you wish to collaborate.

**Comment by polyipseity** [comment]
Yes, you are right about the reason why the messages are all marked as coming from terminal plugin itself. Unfortunately, I am not aware of any way to fix it.

Instead, I have added an option "Intercept logging", which is on by default. Disabling it should ensure the message sourc are correct, at the cost of no messages being logged in the developer console provided by the plugin.

It is available since [`3.15.0`](https://github.com/polyipseity/obsidian-terminal/releases/tag/3.15.0).
