### ISSUE TITLE
Adding Conemu or CMDER

### ISSUE THREAD

**Issue by danraymond** [polyipseity/obsidian-terminal#6]
Hello,

This is a wonderful addition to Obsidian. It's changed how I develop HUGO projects and others.

I cannot seem to get adding either Conemu or CMDER to work. It shows a python error  "terminal exited 9009" if I use CMDER and "terminal exited 123" for Conemu.

Any suggestions??

**Comment by polyipseity** [comment]
I just looked up and tried the programs and I see that Cmder uses ConEmu internally, so the below should just apply to Cmder as well.

The problem is that ConEmu is a [terminal emulator](https://conemu.github.io/en/TerminalVsShell.html). However, the integrated terminal in Obsidian is already a terminal emulator itself, so what you are asking is connecting a terminal emulator to a terminal emulator, which does not work. A terminal emulator can only connect to a shell. Unless ConEmu can also act as a shell at the same time, I don't think there is a good way to integrate it. (Maybe you could ask the ConEmu community.) You can, however, just set it as an external terminal in the settings.

However, if you are just looking for ConEmu's style like
```@ C:\Users\(username)```
rather than
```C:\Users\(username)>```,
I found that running `(ConEmu installation)\ConEmu\CmdInit.cmd` after the terminal is opened is sufficient. (The terminal executable needs to be the default `cmd`.) There is a undocumented way to automatically run said script when the terminal opens, but it is broken right now, so I cannot show it here. (Besides, I am planning to add terminal profiles, which will break this undocumented method.)

With regrads to the Python errors, they are just a consequence of ConEmu not being a shell.

**Comment by polyipseity** [comment]
I am going to leave this issue open for now because adding support to run `(ConEmu installation)\ConEmu\CmdInit.cmd` is an enhancement that I could do. I should also improve the `README.md` to tell people that specifying a terminal emulator for integrated terminal does not work.

(A side question, just curious, what is HUGO?)

**Comment by danraymond** [comment]
Hi,

And thank you so much for taking the time to investigate and respond.
CMD.exe works okay so I may stick with that, but its not pretty. An
external terminal is what I use now but having it integrated is really very
neat.

HUGO is a static site generator for web sites. I have been able to use
obsidian as a development environment which works fantastic for me at least!

Thank you again

Dan Raymond

**Comment by danraymond** [comment]
Could Wezterm be used?? not sure of its also a terminal with same issues as Conemu. Guess searching for something other than cmd.exe

**Comment by polyipseity** [comment]
No, Wezterm is also a terminal emulator. I have added information about shells and terminal emulators to reduce confusion. (25df148d992056b8378ff42d459120f4c48b52f3)

Also,
> I am going to leave this issue open for now because adding support to run `(ConEmu installation)\ConEmu\CmdInit.cmd` is an enhancement that I could do. I should also improve the `README.md` to tell people that specifying a terminal emulator for integrated terminal does not work.

With the latest version (3.1.0), you can finally specify arguments in the settings UI. If you want to just emulate the experience of ConEmu inside `cmd`, you can follow below:
1. Update plugin to the latest version.
2. Add a profile by choosing `cmd: Integrated`.
3. Edit the profile.
4. Name the profile `ConEmu` or any other name you like.
5. Edit arguments. Add two arguments. Specify `/K` for the first one. Specify `(ConEmu installation)\ConEmu\CmdInit.cmd` for the second one.
6. Exit settings. It should automatically save.
7. Open the command palette and select `Terminal: Open terminal: Select`.
8. Choose the newly created profile.
9. You should get a `cmd` terminal but with ConEmu green text.

If you want it to be the default profile when pressing `Terminal: Open terminal: Integrated`, move the profile to the top in the profile list settings.

Let me know if this works for you.
