### ISSUE TITLE
shortcut for clearing terminal on mac

### ISSUE THREAD

**Issue by djwgit** [polyipseity/obsidian-terminal#7]
people use cmd+k often to clear the terminal, possible to add that?

could use command clear, cmd+k is more handy tho.

thanks for this nice plugin!

**Comment by polyipseity** [comment]
Added in 9a384ff055709300069386258ff447fd27affbe9. The combination is `Cmd+K` on macOS and `Ctrl+Shift+K` everywhere else. You will need to update to 3.1.0 to use them.

I also added two extra hotkeys. You can see them in `README.md`:
- FInd in terminal: `Ctrl`+`Shift`+`F`, `Cmd`+`F`
- Focus/unfocus terminal: `Ctrl`+`Shift`+`` ` ``, `Cmd`+`` ` ``

**Comment by djwgit** [comment]
@polyipseity 
thanks for adding this...

one minor thing on mac
after Cmd+K, the terminal window does not have the  shell prompt, as below
<img width="801" alt="terminal" src="https://user-images.githubusercontent.com/10054216/221048051-e01cd458-7da1-4f1f-a501-5676aeb207b7.png">

**Comment by polyipseity** [comment]
This is intentional. The command clears the terminal by removing all text
instead of sending a `clear` command to the shell.

The reason why a `clear` command is not sent is because:
- It does not work when you are running a long-running program, like vim,
unless you exit the program.
- It does not work when you have typed something into the prompt unless you
clear it. Otherwise it will run `(whatever you have typed)clear` instead of
`clear`, which is an invalid command.

I just looked at how VSCode handles this and they also seem to do the same
except for one thing: They keep text on the line your cursor is currently
on, which works for most cases. So I aligned the behavior to that, which
will be available in the next release.
(a4d36d59724b015c3899f9c37088f3e1efe67755)
